config/routes.rb
Rails.application.routes.draw do
  resources :ssessions
  resources :reservations
  resources :group_sessions
  resources :expert_profiles
  resources :profiles
 
  devise_for :buyers, :controllers => { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' },  type: 'Buyer'
  devise_for :users, :controllers => { :sessions => 'sessions', registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  
  devise_for :experts,  type: 'Expert'
   match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :accounts
  resources :tests
  get 'static/registracija' => 'static#registracija'
   get 'book' => 'static#book'
  get 'how-it-works' => 'static#howitworks'
  get 'list-your-services' => 'static#listyourservices'
  get 'terms-of-use' => 'static#termsofuse'
  get 'privacy-policies' => 'static#privacypolicies'
  get '/google9d1b606064f7c612.html', :to => redirect('/google9d1b606064f7c612.html')
    resources :users, only: [:show, :update, :destroy]
   
  
  

  root 'tests#new'

end

app/models/expert_profile.rb
class ExpertProfile < ActiveRecord::Base
    has_many :users, dependent: :destroy
    has_many :group_sessions, dependent: :destroy
   accepts_nested_attributes_for :users
   
    scope :listed, -> { where(listed: 't') }
    scope :unlisted, -> { where(listed: 'f') }
    
     has_many :attachments, dependent: :destroy
    accepts_nested_attributes_for :attachments,  allow_destroy: true
   has_many :reservations
end

app/controllers/expert_profiles_controller.rb
class ExpertProfilesController < ApplicationController
  before_action :set_expert_profile, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user2!, only: [ :edit, :update, :destroy]
  # GET /expert_profiles
  # GET /expert_profiles.json
  def index
  if params[:etype]
    
   @expert_profiles=ExpertProfile.where(expert_type: params[:etype])
  else
 @q=ExpertProfile.ransack(params[:q])
   @expert_profiles = @q.result(distinct: true)
 end
  end

  # GET /expert_profiles/1
  # GET /expert_profiles/1.json
  def show
    @group_sessions= @expert_profile.group_sessions
  end

  # GET /expert_profiles/new
  def new
    @expert_profile = ExpertProfile.new
    
  end

  # GET /expert_profiles/1/edit
  def edit
       @expert_profile.attachments.build
       @group_sessions=current_user.expert_profile.group_sessions
        
  end

  # POST /expert_profiles
  # POST /expert_profiles.json
  def create
    @expert_profile = ExpertProfile.new(expert_profile_params)

    respond_to do |format|
      if @expert_profile.save
        if params[:images]
        
        image=params[:images][0]
          @expert_profile.attachments.create(image: image)
     end
    
        if params[:medias]
        
        params[:medias].each { |media|
          @expert_profile.attachments.create(media: media)
        }
      end
        format.html { redirect_to @expert_profile, notice: 'Expert profile was successfully created.' }
        format.json { render :show, status: :created, location: @expert_profile }
      else
        format.html { render :new }
        format.json { render json: @expert_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expert_profiles/1
  # PATCH/PUT /expert_profiles/1.json
  def update
    respond_to do |format|
      if @expert_profile.update(expert_profile_params)
        if params[:images]
        
        params[:images].each { |image|
          @expert_profile.attachments.create(image: image)
        } 
       
      end
      if params[:medias]
        
        params[:medias].each { |media|
          @expert_profile.attachments.create(media: media)
        }
      
      end
        format.html { redirect_to @expert_profile, notice: 'Expert profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @expert_profile }
      else
        format.html { render :edit }
        format.json { render json: @expert_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expert_profiles/1
  # DELETE /expert_profiles/1.json
  def destroy
    @expert_profile.destroy
    respond_to do |format|
      format.html { redirect_to expert_profiles_url, notice: 'Expert profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert_profile
      @expert_profile = ExpertProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expert_profile_params
      params.require(:expert_profile).permit(:q, :images, :medias, :add1, :add2, :city, :state, :zip, :avatar, :first_name_text, :last_name_text, :display_name, :expert_type, :foo, :availability, :about, :price, :session_length, :experience, :ages_suitable, :skill_levels, :travel, :studio_facility, :credentials, :listed, :user_id, attachments_attributes: [:id, :image, :media, :expert_profile_id, :image_file_name, :image_content_type, :image_file_size, :image_updated_at,:media_file_name, :media_content_type, :media_file_size, :media_updated_at, :_destroy])
    end
end

app/helpers/expert_profiles_helper.rb
module ExpertProfilesHelper
end

app/views/expert_profiles/_buyer_header.html.erb
<body class="dashboard">
  <div class="wrapper">
    <div class='header'>
<nav class='navbar' role='navigation'>
<div class='container'>
<div class='navbar-header'>
<%= link_to "Kuju", root_path, class: "navbar-brand", method: :get %>
</div>
<div class='collapseee' id='top-header'>
<div class='search col-xs-6'>
<!--<form action='/searches' method='get'>-->
<!--<i class='fa fa-search'></i>-->
<!--<input class='nav_search query' name='query' placeholder='Search for trainers, classes. etc.' type='text'>-->
<!--<input class='location nav_search' name='location' placeholder='Where?' type='text'>-->
<!--<button class='btn search-submit bold'>GO</button>-->
<!--</form>-->
</div>
<ul class='nav navbar-nav navbar-right'>
<li>
<%= link_to "BROWSE", expert_profiles_path, method: :get %>
</li>
<li class="divider-vertical"></li>
<li class='dropdown'>
<a aria-expanded='false' class='buyer dropdown-toggle' data-toggle='dropdown' href='#' id='profile-menu'>
<img alt="User default" class="img-circle" src="https://kuju.io/assets/user-default-57dcbb2ec936b04eaca2261902dfd5bd.jpg" />
<span class='nav_user_name'><% if user_signed_in? %>
  <%= current_user.first_name %>
<% end %></span>
<i class='fa fa-angle-down direction'></i>
</a>
<ul aria-labelledby='profile-menu' class='dropdown-menu w-100' id='profile-dropdown' role='menu'>
<li>
<a href="/accounts">Appointments</a>
</li>
<!--<li>-->
<!--<a href="/messages">Messages</a>-->
<!--</li>-->
<li>
<%= link_to('Account settings', edit_user_registration_path, method: :get) %> 
</li>
<li>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   
</li>
</ul>
</li>
</ul>
</div>
</div>
</nav>
</div>

    

app/views/expert_profiles/_expert_header.html.erb
<body class="dashboard">
  <div class="wrapper">
    <div class='header'>
<nav class='navbar' role='navigation'>
<div class='container'>
<div class='navbar-header'>
<%= link_to "Kuju", root_path, class: "navbar-brand", method: :get %>
</div>
<div class='collapseee' id='top-header'>
<ul class='nav navbar-nav navbar-right'>
<li>
 <%= link_to("BROWSE", expert_profiles_path, method: :get)%>
</li>
<% if user_signed_in? %>
<li class='dropdown'>
<a aria-expanded='false' class='dropdown-toggle expert' data-toggle='dropdown' href='#' id='profile-menu'>
<img alt="User default" class="img-circle" src="https://kuju.io/assets/user-default-57dcbb2ec936b04eaca2261902dfd5bd.jpg" />
<span class='nav_user_name'>
  <%= current_user.first_name %>
</span>
<i class='fa fa-angle-down direction'></i>
</a>
<ul aria-labelledby='profile-menu' class='dropdown-menu w-100' id='profile-dropdown' role='menu'>
<li>
<a href="/accounts">Appointments</a>
</li>
<li>
 <%= link_to("My profile", expert_profile_path(current_user.expert_profile.id), method: :get) %>
</li>
<li>
 <%= link_to("Edit profile", edit_expert_profile_path(current_user.expert_profile.id), method: :get) %>
</li>
<li>
<%= link_to("Account settings", edit_user_registration_path(current_user.id), method: :get) %>
</li>
<li>
<a data-method="delete" href="/users/sign_out" rel="nofollow">Log Out</a>
</li>
</ul>
</li>
<% end %>
</ul>
</div>
</div>
</nav>
</div>

   

app/views/expert_profiles/_form.html.erb
<%= form_for(@expert_profile) do |f| %>
  <% if @expert_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expert_profile.errors.count, "error") %> prohibited this expert_profile from being saved:</h2>

      <ul>
      <% @expert_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :add1 %><br>
    <%= f.text_field :add1 %>
  </div>
  <div class="field">
    <%= f.label :add2 %><br>
    <%= f.text_field :add2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :first_name_text %><br>
    <%= f.text_field :first_name_text %>
  </div>
  <div class="field">
    <%= f.label :last_name_text %><br>
    <%= f.text_field :last_name_text %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :expert_type %><br>
    <%= f.text_field :expert_type %>
  </div>
  <div class="field">
    <%= f.label :foo %><br>
    <%= f.text_field :foo %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :session_length %><br>
    <%= f.text_field :session_length %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :ages_suitable %><br>
    <%= f.text_field :ages_suitable %>
  </div>
  <div class="field">
    <%= f.label :skill_levels %><br>
    <%= f.text_field :skill_levels %>
  </div>
  <div class="field">
    <%= f.label :travel %><br>
    <%= f.check_box :travel %>
  </div>
  <div class="field">
    <%= f.label :studio_facility %><br>
    <%= f.check_box :studio_facility %>
  </div>
  <div class="field">
    <%= f.label :credentials %><br>
    <%= f.text_area :credentials %>
  </div>
  <div class="field">
    <%= f.label :listed %><br>
    <%= f.text_field :listed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expert_profiles/edit.html.erb
<%= render 'form2' %>

app/views/expert_profiles/new.html.erb
<h1>New Expert Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', expert_profiles_path, method: :get %>