config/routes.rb
Rails.application.routes.draw do
  resources :ssessions
  resources :reservations
  resources :group_sessions
  resources :expert_profiles
  resources :profiles
 
  devise_for :buyers, :controllers => { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' },  type: 'Buyer'
  devise_for :users, :controllers => { :sessions => 'sessions', registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  
  devise_for :experts,  type: 'Expert'
   match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :accounts
  resources :tests
  get 'static/registracija' => 'static#registracija'
   get 'book' => 'static#book'
  get 'how-it-works' => 'static#howitworks'
  get 'list-your-services' => 'static#listyourservices'
  get 'terms-of-use' => 'static#termsofuse'
  get 'privacy-policies' => 'static#privacypolicies'
  get '/google9d1b606064f7c612.html', :to => redirect('/google9d1b606064f7c612.html')
    resources :users, only: [:show, :update, :destroy]
   
  
  

  root 'tests#new'

end

app/models/group_session.rb
class GroupSession < ActiveRecord::Base
    belongs_to :expert_profile
end

app/controllers/group_sessions_controller.rb
class GroupSessionsController < ApplicationController
  before_action :set_group_session, only: [:show, :edit, :update, :destroy]

  # GET /group_sessions
  # GET /group_sessions.json
  def index
    @group_sessions = GroupSession.all
  end

  # GET /group_sessions/1
  # GET /group_sessions/1.json
  def show
  end

  # GET /group_sessions/new
  def new
    @group_session = GroupSession.new
  end

  # GET /group_sessions/1/edit
  def edit
  end

  # POST /group_sessions
  # POST /group_sessions.json
  def create
    @group_session = GroupSession.new(group_session_params)

    respond_to do |format|
      if @group_session.save
         
        format.html { redirect_to @group_session, notice: 'Group session was successfully created.' }
        format.json { render :show, status: :created, location: @group_session }
      else
        format.html { render :new }
        format.json { render json: @group_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_sessions/1
  # PATCH/PUT /group_sessions/1.json
  def update
    respond_to do |format|
    
      if @group_session.update(group_session_params)
         
        format.html { redirect_to @group_session, notice: 'Group session was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_session }
      else
        format.html { render :edit }
        format.json { render json: @group_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_sessions/1
  # DELETE /group_sessions/1.json
  def destroy
    @group_session.destroy
    respond_to do |format|
      format.html { redirect_to "#{edit_expert_profile_path(@group_session.expert_profile)}#group_sessions", notice: 'Group session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_session
      @group_session = GroupSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_session_params
      params.require(:group_session).permit(:title, :price, :capacity, :description, :expert_profile_id).merge(expert_profile_id: current_user.expert_profile_id)
    end
end

app/helpers/group_sessions_helper.rb
module GroupSessionsHelper
end

app/views/group_sessions/_form.html.erb
<%= form_for(@group_session) do |f| %>
  <% if @group_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_session.errors.count, "error") %> prohibited this group_session from being saved:</h2>

      <ul>
      <% @group_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_sessions/edit.html.erb
<h1>Editing Group Session</h1>

<%= render 'form' %>

app/views/group_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Group Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Capacity</th>
      <th>Description</th>
      <th>Expert profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_sessions.each do |group_session| %>
      <tr>
        <td><%= group_session.title %></td>
        <td><%= group_session.price %></td>
        <td><%= group_session.capacity %></td>
        <td><%= group_session.description %></td>
        <td><%= group_session.expert_profile_id %></td>
        <td><%= link_to 'Show', group_session %></td>
        <td><%= link_to 'Edit', edit_group_session_path(group_session) %></td>
        <td><%= link_to 'Destroy', group_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group session', new_group_session_path %>

app/views/group_sessions/new.html.erb
<h1>New Group Session</h1>

<%= render 'form' %>

<%= link_to 'Back', group_sessions_path %>

app/views/group_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @group_session.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @group_session.price %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @group_session.capacity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group_session.description %>
</p>



<%= link_to 'Edit', edit_group_session_path(@group_session) %> |
<%= link_to 'Back', "#{edit_expert_profile_path(@group_session.expert_profile)}#group_sessions", method: :get  %>