config/routes.rb
Rails.application.routes.draw do
  resources :ssessions
  resources :reservations
  resources :group_sessions
  resources :expert_profiles
  resources :profiles
 
  devise_for :buyers, :controllers => { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' },  type: 'Buyer'
  devise_for :users, :controllers => { :sessions => 'sessions', registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  
  devise_for :experts,  type: 'Expert'
   match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :accounts
  resources :tests
  get 'static/registracija' => 'static#registracija'
   get 'book' => 'static#book'
  get 'how-it-works' => 'static#howitworks'
  get 'list-your-services' => 'static#listyourservices'
  get 'terms-of-use' => 'static#termsofuse'
  get 'privacy-policies' => 'static#privacypolicies'
  get '/google9d1b606064f7c612.html', :to => redirect('/google9d1b606064f7c612.html')
    resources :users, only: [:show, :update, :destroy]
   
  
  

  root 'tests#new'

end

app/models/ssession.rb
class Ssession < ActiveRecord::Base
    belongs_to :reservation
    
    before_create :set_dateformat
    
    scope :past_sessions, ->  { where('date < ?', Date.today.to_s) }
    scope :future_sessions, ->  { where('date >= ?', Date.today.to_s) }
    
    def set_dateformat
    
    self.date =Date.strptime(self.date, '%m/%d/%Y') 

    end
    
end

app/controllers/ssessions_controller.rb
class SsessionsController < ApplicationController
  before_action :set_ssession, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  # GET /ssessions
  # GET /ssessions.json
  def index
    @ssessions = Ssession.all
  end

  # GET /ssessions/1
  # GET /ssessions/1.json
  def show
  end

  # GET /ssessions/new
  def new
    @ssession = Ssession.new
  end

  # GET /ssessions/1/edit
  def edit
  end

  # POST /ssessions
  # POST /ssessions.json
  def create
    @ssession = Ssession.new(ssession_params)
   
    respond_to do |format|
      if @ssession.save
        format.html { redirect_to @ssession, notice: 'Ssession was successfully created.' }
        format.json { render :show, status: :created, location: @ssession }
      else
        format.html { render :new }
        format.json { render json: @ssession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ssessions/1
  # PATCH/PUT /ssessions/1.json
  def update
    respond_to do |format|
      if @ssession.update(ssession_params)
        format.html { redirect_to accounts_url}
        format.json { render :show, status: :ok, location: @ssession }
      else
        format.html { render :edit }
        format.json { render json: @ssession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ssessions/1
  # DELETE /ssessions/1.json
  def destroy
    @ssession.destroy
    respond_to do |format|
      format.html { redirect_to ssessions_url, notice: 'Ssession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ssession
      @ssession = Ssession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ssession_params
      params.require(:ssession).permit(:reservation_id, :date, :time, :user_id, :expert_profile_id, :canceled)
    end
end

app/helpers/ssessions_helper.rb
module SsessionsHelper
end

app/views/ssessions/_form.html.erb
<%= form_for(@ssession) do |f| %>
  <% if @ssession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ssession.errors.count, "error") %> prohibited this ssession from being saved:</h2>

      <ul>
      <% @ssession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reservation_id %><br>
    <%= f.number_field :reservation_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ssessions/edit.html.erb
<h1>Editing Ssession</h1>

<%= render 'form' %>

<%= link_to 'Show', @ssession %> |
<%= link_to 'Back', ssessions_path %>

app/views/ssessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ssessions</h1>

<table>
  <thead>
    <tr>
      <th>Reservation</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ssessions.each do |ssession| %>
      <tr>
        <td><%= ssession.reservation_id %></td>
        <td><%= ssession.date %></td>
        <td><%= ssession.time %></td>
        <td><%= link_to 'Show', ssession %></td>
        <td><%= link_to 'Edit', edit_ssession_path(ssession) %></td>
        <td><%= link_to 'Destroy', ssession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ssession', new_ssession_path %>

app/views/ssessions/new.html.erb
<h1>New Ssession</h1>

<%= render 'form' %>

<%= link_to 'Back', ssessions_path %>

app/views/ssessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reservation:</strong>
  <%= @ssession.reservation_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @ssession.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @ssession.time %>
</p>

<%= link_to 'Edit', edit_ssession_path(@ssession) %> |
<%= link_to 'Back', ssessions_path %>