config/routes.rb
Rails.application.routes.draw do
  resources :ssessions
  resources :reservations
  resources :group_sessions
  resources :expert_profiles
  resources :profiles
 
  devise_for :buyers, :controllers => { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' },  type: 'Buyer'
  devise_for :users, :controllers => { :sessions => 'sessions', registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  
  devise_for :experts,  type: 'Expert'
   match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :accounts
  resources :tests
  get 'static/registracija' => 'static#registracija'
   get 'book' => 'static#book'
  get 'how-it-works' => 'static#howitworks'
  get 'list-your-services' => 'static#listyourservices'
  get 'terms-of-use' => 'static#termsofuse'
  get 'privacy-policies' => 'static#privacypolicies'
  get '/google9d1b606064f7c612.html', :to => redirect('/google9d1b606064f7c612.html')
    resources :users, only: [:show, :update, :destroy]
   
  
  

  root 'tests#new'

end

app/models/account.rb
class Account < ActiveRecord::Base
 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  # GET /accounts
  # GET /accounts.json
  def index
    if current_user.type=="Buyer" && current_user.admin_check !="true"
            @future=0
            @past=0
            @canceled=0
          current_user.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.date>=Date.today.to_s
            @future=1
          end
          end
          end
          current_user.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.date<Date.today.to_s
            @past=1
          end
          end
          end
          current_user.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.canceled=="true"
            @canceled=1
          end
          end
          end
         render  "buyer_reservation" 
  elsif current_user.type=="Expert" && current_user.admin_check !="true"
           @futureex=0
            @pastex=0
            @canceledex=0
            if current_user.present?
          current_user.expert_profile.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.date>=Date.today.to_s
            @futureex=1
          end
          end
          end
          current_user.expert_profile.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.date<Date.today.to_s
            @pastex=1
          end
          end
          end
          current_user.expert_profile.reservations.each do |reservation| 
          reservation.ssessions.each do |ssession|
          if ssession.canceled=="true"
            @canceledex=1
          end
          end
          end
        end
       render  "expert_reservation" 
 elsif current_user.admin_check=="true"
        @exp=User.experts
        @byr=User.buyers
        render  "admin_panel"
  end
   

  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :email, :uid)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_buyer_header.html.erb
<body class="dashboard">
  <div class="wrapper">
    <div class='header'>
<nav class='navbar' role='navigation'>
<div class='container'>
<div class='navbar-header'>
<%= link_to "Kuju", root_path, class: "navbar-brand", method: :get %>
</div>
<div class='collapseee' id='top-header'>
<div class='search col-xs-6'>
<!--<form action='/searches' method='get'>-->
<!--<i class='fa fa-search'></i>-->
<!--<input class='nav_search query' name='query' placeholder='Search for trainers, classes. etc.' type='text'>-->
<!--<input class='location nav_search' name='location' placeholder='Where?' type='text'>-->
<!--<button class='btn search-submit bold'>GO</button>-->
<!--</form>-->

</div>
<ul class='nav navbar-nav navbar-right'>
<li>
<%= link_to "BROWSE", expert_profiles_path, method: :get %>
</li>
<li class="divider-vertical"></li>
<li class='dropdown'>
<a aria-expanded='false' class='buyer dropdown-toggle' data-toggle='dropdown' href='#' id='profile-menu'>
<img alt="User default" class="img-circle" src="https://kuju.io/assets/user-default-57dcbb2ec936b04eaca2261902dfd5bd.jpg" />
<span class='nav_user_name'><% if user_signed_in? %>
  <%= current_user.first_name %>
<% end %></span>
<i class='fa fa-angle-down direction'></i>
</a>
<ul aria-labelledby='profile-menu' class='dropdown-menu w-100' id='profile-dropdown' role='menu'>
<li>
<a href="/accounts">Appointments</a>
</li>
<!--<li>-->
<!--<a href="/messages">Messages</a>-->
<!--</li>-->
<li>
<%= link_to('Account settings', edit_user_registration_path, :method => :get) %> 
</li>
<li>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   
</li>
</ul>
</li>
</ul>
</div>
</div>
</nav>
</div>

    <div class='topmenu'>
<nav class='navbar' role='navigation'>
<div class='buyer container'>
<div class='nopad-l' id='top-menu'>
<ul class='nav navbar-nav'>
<!-- / EXPERT & BUYER SECTION -->
<li class='first'>
  <%= link_to "APPOINTMENTS", accounts_path, :class => "active" %>

</li>
<!--<li>-->
<!--<a href='/messages'>-->
<!--MESSAGES-->

<!--</a>-->
<!--</li>-->
<li>
<%= link_to('ACCOUNT SETTINGS', edit_user_registration_path, :method => :get) %> 
</li>
</ul>
</div>
</div>
</nav>
</div>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/admin_panel.html.erb
<body class="dashboard">
  <div class="wrapper">
    <div class='header'>
<nav class='navbar' role='navigation'>
<div class='container'>
<div class='navbar-header'>
<%= link_to "Kuju", root_path, class: "navbar-brand", method: :get %>
</div>
<div class='collapseee' id='top-header'>
<div class='search col-xs-6'>
<!--<form action='/searches' method='get'>-->
<!--<i class='fa fa-search'></i>-->
<!--<input class='nav_search query' name='query' placeholder='Search for trainers, classes. etc.' type='text'>-->
<!--<input class='location nav_search' name='location' placeholder='Where?' type='text'>-->
<!--<button class='btn search-submit bold'>GO</button>-->
<!--</form>-->

</div>
<ul class='nav navbar-nav navbar-right'>
<li>
<%= link_to "BROWSE", expert_profiles_path, method: :get %>
</li>
<li class="divider-vertical"></li>
<li class='dropdown'>
<a aria-expanded='false' class='buyer dropdown-toggle' data-toggle='dropdown' href='#' id='profile-menu'>
<img alt="User default" class="img-circle" src="https://kuju.io/assets/user-default-57dcbb2ec936b04eaca2261902dfd5bd.jpg" />
<span class='nav_user_name'><% if user_signed_in? %>
  <%= current_user.first_name %>
<% end %></span>
<i class='fa fa-angle-down direction'></i>
</a>
<ul aria-labelledby='profile-menu' class='dropdown-menu w-100' id='profile-dropdown' role='menu'>

<li>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   
</li>
</ul>
</li>
</ul>
</div>
</div>
</nav>
</div>



<h3>Listing Experts</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @exp.each do |expert| %>
      <tr>
        <td><%= expert.first_name %> <%= expert.last_name %></td>
        <td><%= expert.email %></td>
        <td class="success"><%= link_to 'Change to Buyer', user_path(expert, user: {type: :Buyer}), method: :put, data: { confirm: 'Are you sure?' } %></td>
          <td class="danger"><%= link_to 'DELETE USER', user_path(expert), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<h3>Listing Buyers</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @byr.each do |buyer| %>
   <% if buyer.admin_check!="true" %>
      <tr>
        <td><%= buyer.first_name %> <%= buyer.last_name %></td>
        <td><%= buyer.email %></td>
        <td class="success"><%= link_to 'Change to Expert', user_path(buyer, user: {type: :Expert}), method: :put, data: { confirm: 'Are you sure?' } %></td>
        <td class="danger"><%= link_to 'DELETE USER', user_path(buyer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
        
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/accounts/buyer_reservation.html.erb
<%= render 'buyer_header' %>
<!--<div class='container'>-->
<!--<div class='col-xs-12 nopad'>-->
<!--<div class='alert alert-notice alert-verification vc'>-->
<!--<span>PLEASE VERIFY YOUR EMAIL TO COMPLETE YOUR REGISTRATION!</span>-->
<!--<button class='navbar-right btn btn-success resend-verify-email'>RESEND VERIFICATION EMAIL</button>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->

<div class='container fitted expert-dashboard'>
<div class='row reserv-page'>
<div class='col-xs-12 reservations white next'>
<div class='panel-header'>
<h5 class='text-light'>
UPCOMING APPOINTMENTS
<a class='navbar-right inverse' href='/reservations?show=up'>ALL UPCOMING APPOINTMENTS</a>
</h5>
</div>

<% if (current_user.reservations.present? && @future==1) %>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Expert</th>
      <th>Cancelation</th>
      
     
      
    </tr>
  </thead>

  <tbody>
      <% current_user.reservations.each do |reservation| %>
    <% reservation.ssessions.each do |ssession| %>
    <% if ssession.date >= Date.today.to_s && ssession.canceled!="true" %>
      <tr>
        <td ><%= ssession.date %></td>
        <td><%= ssession.time %></td>
        <td><%= link_to ssession.reservation.expert_profile.display_name,ssession.reservation.expert_profile  %></td>
         <td class="danger"><%= link_to 'Cancel', ssession_path(ssession, ssession: {canceled: :true}), method: :put, data: { confirm: 'Are you sure?' } %></td>
        
        
       
        
      
      </tr>
      <% end %>
       <% end %>
    <% end %>
  </tbody>
</table>

<% else %>


<p>You have no appointments.</p>
<% end %>

</div>
<div class='col-xs-12 reservations white next'>
<div class='panel-header'>
<h5 class='text-light'>
PAST APPOINTMENTS
<a class='navbar-right inverse' href='/reservations?show=past'>ALL PAST APPOINTMENTS</a>
</h5>
</div>
<% if (current_user.reservations.present? && @past==1) %>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Expert</th>
      
     
      
    </tr>
  </thead>

  <tbody>
      <% current_user.reservations.each do |reservation| %>
    <% reservation.ssessions.each do |ssession| %>
    <% if ssession.date < Date.today.to_s && ssession.canceled!="true" %>
      <tr  gsid=group_session.id>
        <td ><%= ssession.date %></td>
        <td><%= ssession.time %></td>
        <td><%= link_to ssession.reservation.expert_profile.display_name,ssession.reservation.expert_profile  %></td>
        
        
       
        
      
      </tr>
      <% end %>
       <% end %>
    <% end %>
  </tbody>
</table>

<% else %>


<p>You have no appointments.</p>
<% end %>

</div>
<!--<div class='col-xs-12 reservations white next'>-->
<!--<div class='panel-header'>-->
<!--<h5 class='text-light'>-->
<!--PACKAGES-->
<!--</h5>-->
<!--</div>-->

<!--</div>-->
<div class='col-xs-12 reservations white next'>
<div class='panel-header'>
<h5 class='text-light'>
CANCELED APPOINTMENTS
<a class='navbar-right inverse' href='/reservations?show=canceled'>ALL CANCELED APPOINTMENTS</a>
</h5>
</div>
<% if (current_user.reservations.present? && @canceled==1) %>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Expert</th>
      
     
      
    </tr>
  </thead>

  <tbody>
      <% current_user.reservations.each do |reservation| %>
    <% reservation.ssessions.each do |ssession| %>
    <% if  ssession.canceled=="true" %>
      <tr  gsid=group_session.id>
        <td ><%= ssession.date %></td>
        <td><%= ssession.time %></td>
        <td><%= link_to ssession.reservation.expert_profile.display_name,ssession.reservation.expert_profile  %></td>
        
        
        
       
        
      
      </tr>
      <% end %>
       <% end %>
    <% end %>
  </tbody>
</table>

<% else %>


<p>You have no appointments.</p>
<% end %>

</div>
</div>
</div>
<div aria-labelledby='r-cancel' class='modal' id='r-cancel'>
<div class='modal-dialog'>
<div class='modal-content'>
<div class='modal-header'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='modal-title'>CANCEL SESSION</h4>
</div>
<div class='modal-body'>
<p class='text-light desc'>Are you sure you want to cancel this session? If so, please let the pro know the reason. Your money <span class="price">$</span> will be refunded. You can also <a class="inverse">reschedule the session</a> if theres a schedule conflict.</p>
<div class='form'>
<textarea id='cancelation-reason' pattern='.{50,500}' rows='4'></textarea>
</div>
<div class='vc w-100'>
<div class='nice-checkbox'>
<i class='fa fa-check-square-o'></i>
<i class='fa fa-square-o'></i>
<input id='cancel-read' type='checkbox'>
</div>
<span>I have read and agree to the <a class="inverse">cancellation policy</a>.</span>
</div>
<br>
<div class='w-100'>
<a class='btn cancel-btn' disabled path='/reservations'>YES, CANCEL THIS SESSION</a>
<a class='btn btn-success' data-dismiss='modal' path='/trainer_sessions'>NO, KEEP THIS SESSION</a>
<img alt="Preloader" class="preloader" src="https://kuju.io/assets/preloader-a130e0797a5836f18e306ebdf7ba6acc.gif" style="display:none;" />
</div>
</div>
</div>
</div>
</div>

<div aria-labelledby='add_review' class='modal' id='add_review'>
<div class='modal-dialog'>
<div class='modal-content'>
<div class='modal-header' style='border: none'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='modal-title'>WRITE REVIEW</h4>
</div>
<div class='modal-body'>
<div class='form'>
<label class='mp'>RATING</label>
<input class="hide ratings" id="points" name="points" type="text" />
<label class='mt'>WRITE YOUR REVIEW</label>
<textarea id="comment" maxlength="254" name="comment" placeholder="Tell about your experience" rows="7">
</textarea>
</div>
<a class='btn btn-success review-btn w-100' path='/reviews'>SUBMIT REVIEW</a>
</div>
</div>
</div>
</div>

<div aria-labelledby='r-info' class='modal' id='r-info'>
<div class='modal-dialog'>
<div class='modal-content ready' style='display:none'></div>
<div class='modal-content preloader'>
<div class='modal-header'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='name modal-title'>PLEASE WAIT...</h4>
</div>
<div class='modal-body w-100'>
<img alt="Preloader" src="https://kuju.io/assets/preloader-a130e0797a5836f18e306ebdf7ba6acc.gif" />
</div>
</div>
</div>
</div>

<div aria-labelledby='r-reschedule' class='modal' id='r-reschedule'>
<div class='modal-dialog modal-sm'>
<div class='modal-content'>
<div class='modal-header'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='modal-title'>RESCHEDULE SESSION</h4>
</div>
<div class='modal-body'>
<p class='text-light desc'>Are you sure you want to reschedule this session?</p>
<div class='form'>
<div class='col-xs-7 nopad'>
<label style='color: #3b515e'>DATE</label>
<input class='datepicker-r' id='reschedule-date' type='text'>
</div>
<div class='col-xs-5 nopad-r'>
<label style='color: #3b515e'>TIME</label>
<input class='timepickers' id='reschedule-time' type='text'>
</div>
</div>
<br>
<div class='w-100'>
<a class='btn btn-success reschedule-submit' path='/reservations/:id/reschedule'>RESCHEDULE</a>
<a class='btn btn-default' data-dismiss='modal' style='width: 50%;'>CANCEL</a>
<img alt="Preloader" class="preloader" src="https://kuju.io/assets/preloader-a130e0797a5836f18e306ebdf7ba6acc.gif" style="display:none;" />
</div>
</div>
</div>
</div>
</div>

<div aria-labelledby='send-message' class='modal' id='send-message'>
<div class='modal-dialog'>
<div class='modal-content'>
<div class='modal-header'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='modal-title'>
SEND MESSAGE TO
<span class='recipient-name upcase'></span>
</h4>
</div>
<div class='modal-body'>
<div class='form'>
<textarea class='message-text' rows='5'></textarea>
</div>
<br>
<div class='w-100'>
<a class='btn btn-default' data-dismiss='modal'>CANCEL</a>
<a class='btn btn-success send' path='/messages.json'>SEND</a>
<img alt="Preloader" class="preloader" src="https://kuju.io/assets/preloader-a130e0797a5836f18e306ebdf7ba6acc.gif" style="display:none;" />
</div>
</div>
</div>
</div>
</div>


    <div class="push"></div>
  </div>
    <div id="footer-wrapper">
      <div id='footer'>
<div class='container'>
<div class='links w-100'>
<div class='footer-col'>
<h4>FIND</h4>
<ul>
<li>
<a href="/expert_profiles">PERSONAL TRAINERS</a>
</li>
<li>
<a href="/expert_profiles?etype=Yoga">YOGA CLASSES</a>
</li>
<li>
<a href="/expert_profiles?etype=Pilate">PILATES CLASSES</a>
</li>
<li>
<a href="/expert_profiles?etype=Spin">SPIN CLASSES</a>
</li>
<li>
<a href="/expert_profiles?etype=Kickboxing">KICKBOXING</a>
</li>
</ul>
</div>
<div class='footer-col'>
<h4>KUJU</h4>
<ul>
<ul>
<%= link_to "BROWSE", expert_profiles_path, method: :get %>
</ul>
<ul>
<a href="/how-it-works">HOW IT WORKS</a>
</ul>
<ul>
<a href="/list-your-services">LIST YOUR SERVICES</a>
</ul>
<ul>
<a data-target="#contact-modal" data-toggle="modal" href="#">CONTACT US</a>
</ul>
<ul>
<a href="/terms-of-use">TERMS</a>
</ul>
<ul>
<a href="/privacy-policies">PRIVACY</a>
</ul>
</ul>
</div>
<div class='footer-col'>
<h4>GET SOCIAL</h4>
<div class='social-links'>
<a class="circle" href="https://instagram.com/bekuju" target="_blank"><i class='fa fa-instagram'></i></a>
<a class="circle" href="https://facebook.com/bekuju" target="_blank"><i class='fa fa-facebook'></i></a>
<a class="circle" href="https://twitter.com/BeKuju" target="_blank"><i class='fa fa-twitter'></i></a>
</div>
</div>
<div class='fifth-col'>
<a class="navbar-right" href="#" onclick="$(&quot;html, body&quot;).animate({ scrollTop: 0 }, &quot;slow&quot;);return false;"><%= image_tag "logo-green.jpg", :alt => "Logo green" %>
</div>
</div>
<div class='bottom w-100 block'>
<span>&copy; Kuju 2016. All Rights Reserved.</span>
</div>
</div>
</div>
<div aria-labelledby='contact-modal' class='modal' id='contact-modal'>
<div class='modal-dialog'>
<div class='modal-content'>
<div class='modal-header'>
<span class='close' data-dismiss='modal' type='button'>
<span aria-hidden='true'>×</span>
<span class='sr-only'>Close</span>
</span>
<h4 class='modal-title'>CONTACT US</h4>
<p class='text-light'>If you have any questions or comments, feel free to get in touch!</p>
</div>
<div class='modal-body'>
<form accept-charset="UTF-8" action="/contact_us" method="post"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="aWo6EG6a5JVMbCIbhcPUAEReGCvP58Fm3B4FvP3YYn8=" /></div>
<div class='form'>
<input class='name' name='name' placeholder='YOUR NAME' type='text'>
<input class='email' name='email' placeholder='YOUR EMAIL ADDRESS' required type='email'>
<textarea class='message' name='message' placeholder='YOUR MESSAGE' required rows='7'></textarea>
</div>
<button class='btn btn-success w-100 send' type='submit'>SEND MESSAGE</button>
</form>

</div>
</div>
</div>
</div>


    </div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58555994-1', 'auto');
  ga('send', 'pageview');

  </script>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.last_name %></td>
        <td><%= account.email %></td>
      
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path, method: :get %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path, method: :get %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @account.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @account.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @account.uid %>
</p>

<%= link_to 'Edit', edit_account_path(@account), method: :get %> |
<%= link_to 'Back', accounts_path, method: :get %>